CREATE SCHEMA "GESTION";


CREATE TABLE "GESTION"."datosprocesos" (
"IDPROCESO" INTEGER NOT NULL,
"NOMBRE" VARCHAR(30) NOT NULL,
"TAMANIO", INTEGER NOT NULL,
"FECHACREACION", DATE NOT NULL,
"DURACION", INTEGER NOT NULL
)

CREATE TABLE "GESTION"."PROCESOSELIMINADOS" (
"IDPROCESO" INTEGER NOT NULL,
"NOMBRE" VARCHAR(30) NOT NULL,
"TAMANIO", INTEGER NOT NULL,
"FECHAMUERTE", DATE NOT NULL,
"DURACION", INTEGER NOT NULL
)

GRANT CREATEIN ON SCHEMA "ADMINISTRATOR" TO PUBLIC;

